### ISSUE TITLE
Avoid very long lines

### ISSUE THREAD

**Issue by mernst** [AML14/tratto#62]
Files such as guava-19.0_dataCollectedWithJavaParser.json are one long line.  Is it possible to add a newline between top-level elements when creating it?

**Comment by AML14** [comment]
These files are relative to the legacy folder. TBH, I haven't even looked in there, since we're not using it at all. I would either delete the folder or simply not care to maintain it anymore unless we need something that we implemented in there.

**Comment by mernst** [comment]
I see.  If we won't scavenge any of the code or data in the legacy folder, I am in favor of deleting it.  (If some of it should be scavenged, then those parts should be retained.)

**Comment by AML14** [comment]
I just deleted the legacy folder, I checked and I don't think there's anything we needed to save. Regardless, we can always recover it from a previous commit.

**Comment by mernst** [comment]
Thanks!
